[package]
name = "gif2mm2_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.12.0"
rand = "0.8.5"
itertools = "0.10.5"
rayon = "1.7.0"
